### ISSUE TITLE
Free alternative to shape_predictor_68_face_landmarks.dat.bz2

### ISSUE THREAD

**Issue by rsnitsch** [davisking/dlib-models#6]
I have noticed that the `shape_predictor_68_face_landmarks.dat.bz2` model file is not available for commercial use. The dataset that was used to train the model is owned by the Imperial College London.

Do you know of any decent free alternatives that can be used for commercial projects?

So far I have found no way other than creating your own collection of photographs plus annotations.

**Comment by davisking** [comment]
For some reason I didn't get a notification about this issue via email.  It says I'm subscribed.  Huh, hopefully github doesn't keep doing that.

Anyway, I have no idea if you can really use that file in commercial programs.  The university college london guys want to assert that models derived from their data inherit the same licensing restrictions.  I am not a lawyer so I don't know if that's enforceable or not.  It's up to you to figure that out.  I would point out however that all the models pretty much everyone makes are derived from images scraped from the internet and there seems to be general agreement that the licenses on the original files don't prevent this these models from being used in commercial applications.  I don't really see why that wouldn't apply in this case as well.  **But I should emphasize that I don't care, it's not my dataset, and I'm not a lawyer**.  I'm not going to pick a fight about it with the iBug team because I like those guys and have no incentive to do that. 

If I was you I would either talk to a lawyer or email the guys at university college london about it.
